output: Assign1_Prob4.o Set.o
	g++ Assign1_Prob4.cpp -o output



Assign1_Prob4.o:Assign1_Prob4.cpp
	g++ -c Assign1_Prob4.cpp



Set.o:Set.cpp
	g++ -c Set.cpp




clean:
	rm*.o output