output: Assign1_Prob1-2.o Item.o Stack.o
	g++ Assign1_Prob1-2.cpp -o output



Assign1_Prob1-2.o:Assign1_Prob1-2.cpp
	g++ -c Assign1_Prob1-2.cpp



Stack.o:Stack.cpp
	g++ -c Stack.cpp


Item.o:Item.cpp
	g++ -c Item.cpp




clean:
	rm*.o output