output: Assign1_Prob3.o Traveler.o Pager.o BusinessTraveler.o
	g++ Assign1_Prob3.cpp -o output


Assign1_Prob3.o:Assign1_Prob3.cpp
	g++ -c Assign1_Prob3.cpp


Traveler.o:Traveler.cpp Traveler.h
	g++ -c Traveler.cpp


Pager.o:Pager.cpp Pager.h
	g++ -c Pager.cpp


BusinessTraveler.o:BusinessTraveler.cpp BusinessTraveler.h
	g++ -c BusinessTraveler.cpp



clean:
	rm*.o output